[project]
name = "x-template-image-classification"
version = "0.1.0"
description = "Xircuits project template for image classification."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.6",
    "numpy>=2.2.6",
    "tensorflow>=2.20.0",
    "xircuits~=1.20.0a0",
]
