name: Run UI E2E Test

on:
  workflow_dispatch:
    branches: "*"


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set Branch Name
      run: |
        echo "branch_name=${GITHUB_HEAD_REF##*/}" >> $GITHUB_ENV               

    - name: Check Branch
      run: echo "$env.branch_name"

    - name: Get Hash
      id: hash
      run: echo "git_hash=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV

    - name: Check Hash
      run: echo "$env.git_hash"

    - name: Install Xircuits and Project Requirements
      run: |
        pip install -r requirements.txt

    - name: Setup Playwright
      run: |
        cd ui-tests
        npx playwright install --with-deps
        

    - name: Test E2E
      run: |
        ( ls && jupyter lab --NotebookApp.token='' ) & npm install -D @playwright/test && npx playwright test
    
